CC = clang++
TARGET= SOMTest.out
CFLAGS= -arch i386 -stdlib=libstdc++
FILES = SOMTest.cpp libgrt.a
OBJ = hellomake.o hellofunc.o 
INCLUDE = -I /Users/chikashi/Development/grt/GRT

all: $(FILES)
	$(CC) $(CFLAGS) -o $(TARGET) $(INCLUDE) $(LIBS) $(FILES)

